name: compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone reposiory"
        uses: actions/checkout@v2
        with:
          repository: "keedhost/gitaction-test.git"
          ref: "main"
          
      - name: Packages install
        run: |
            sudo apt update
            sudo apt install cppcheck gcc
            
      - name: Compile
        run: |
            cppcheck --std=c99 --std=posix ./main.c
            gcc main.c -o main
        
      - name: Launch
        run: ./main
