name: compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Packages install
        run: |
            sudo apt update
            sudo apt install cppcheck gcc
            
      - name: Compile
        run: |
            ls -lah
            pwd
            gcc gitaction-test/main.c -o main
        
      - name: Launch
        run: ./main
